"""
Django settings for edutrellis project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-2!^^*c(t)whrn^4w3xkoqx!1p85e5s!-xh0w+xai7&q*80tt@@'
)

DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'myapp',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'myapp.middleware.CanonicalHostMiddleware',
    'myapp.middleware.PublicAssetCacheMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'myapp.middleware.HideAdminFromNonStaffMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edutrellis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.business_info.context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'edutrellis.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'myapp' / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default Django session lifetime is 2 weeks, counted from creation — an
# anonymous visitor's cart/AI chat history (both keyed off session_key) would
# silently become unreachable after that, since a new session (and therefore
# a new, empty session_key) gets created on their next visit. Extending this
# to a year and refreshing it on every request means a returning guest keeps
# their data as long as they visit at least once a year, without needing an
# account.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365
SESSION_SAVE_EVERY_REQUEST = True

# GitHub OAuth App credentials for the /AI/ GitHub-mode "Login with GitHub"
# button (myapp/views.py github_oauth_start/callback). Register an OAuth App
# at https://github.com/settings/developers with its Authorization callback
# URL set to <your domain>/AI/api/github/oauth/callback/, then set these two
# env vars. Left unset, the connect panel just falls back to pasting a
# Personal Access Token — nothing breaks, the button simply doesn't appear.
GITHUB_OAUTH_CLIENT_ID = os.environ.get('GITHUB_OAUTH_CLIENT_ID', '')
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', '')

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True




# ── Email (Gmail SMTP via App Password) ─────────────────────────────────────
# All outbound store/site email (order confirmations, contact-lead alerts) is
# sent via this account. Signup/profile verification codes moved to SMS (see
# TWO_FACTOR_API_KEY below) — email is no longer in that path. The
# dashboard's Email Settings page has been deactivated — this is the only
# email path now. Hardcoded on purpose, with NO os.environ.get() indirection
# — a stale EMAIL_HOST_USER/PASSWORD env var left over from earlier SMTP
# testing on a dev machine would otherwise silently override these and
# nobody would know.

EMAIL_BACKEND  = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST     = 'smtp.gmail.com'
EMAIL_PORT     = 587
EMAIL_USE_TLS  = True
EMAIL_USE_SSL  = False

# Fail fast rather than hanging the request for 30+ seconds if Gmail's SMTP
# doesn't respond within 10 seconds.
EMAIL_TIMEOUT  = 10

EMAIL_HOST_USER      = 'edutrellisprivatelimited@gmail.com'
EMAIL_HOST_PASSWORD  = 'tnjwlzgzmnexoufo'
DEFAULT_FROM_EMAIL   = f'EduTrellis <{EMAIL_HOST_USER}>'
LEAD_RECIPIENT_EMAIL = EMAIL_HOST_USER

# ── SMS OTP (2Factor.in) ─────────────────────────────────────────────────────
# Signup/profile phone verification goes over SMS via this API key — a plain
# HTTPS call, so it isn't affected by the Gmail/Titan SMTP delivery problems
# or by Railway potentially blocking outbound SMTP on production.
TWO_FACTOR_API_KEY = '12feb4c9-9636-11f1-9cb1-0200cd936042'

# ── AI Chat (NVIDIA API) ─────────────────────────────────────────────────────
# Powers the public /AI/ chat page (myapp/ai_chat.py). This is a real,
# billable API key — hardcoded here at the user's explicit choice, same as
# the credentials above, which means it's visible in this repo's git
# history to anyone with access. Rotate it in the NVIDIA console if it ever
# needs to change.
NVIDIA_API_KEY = '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'

# Powers the "Gemini 3.6 Flash" entry in the /AI/ model picker
# (myapp/ai_chat.py, MODELS['gemini']), via Google's OpenAI-compatible
# endpoint. Unlike NVIDIA_API_KEY/TAVILY_API_KEY above, this is NOT
# hardcoded — GitHub's push protection rejects it (the key in use here was
# identified as a "GCP API Key Bound to a Service Account", a broader-scoped
# credential type than a plain API key, not just a leftover style choice).
# Set the GEMINI_API_KEY environment variable (same pattern as
# GITHUB_OAUTH_CLIENT_ID/SECRET below) — on Railway, add it in the service's
# Variables tab; locally, set it in your shell before running the server.
# Left unset, that one model just fails per-request with an auth error —
# nothing else breaks.
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# Powers EduTrellis Light's web-search fallback (myapp/web_search.py) when
# the saved knowledge base has nothing relevant — same hardcoding choice and
# same caveat as NVIDIA_API_KEY above. Rotate at app.tavily.com if needed.
TAVILY_API_KEY = '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'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Expose the AI latency breakdown added in views.py/ai_chat.py in the normal
# development and Gunicorn logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'myapp': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


