# Generated by Django 5.2.12 on 2026-08-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_purge_fake_contact_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='ai_display_name',
            field=models.CharField(blank=True, help_text='Name the user gave the AI chat, if any.', max_length=100),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ai_instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram handle the user gave the AI chat, if any (no leading @).', max_length=60),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ai_location',
            field=models.CharField(blank=True, help_text='Location the user gave the AI chat, if any.', max_length=150),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ai_onboarded',
            field=models.BooleanField(default=False, help_text='Already asked the first-time name/location/Instagram question (or the account predates this feature) — never ask again.'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ai_onboarding_pending',
            field=models.BooleanField(default=False, help_text="The question was just asked; the user's next message will be parsed for an answer."),
        ),
    ]
