from django.urls import path
from django.views.generic import RedirectView
from myapp import views

urlpatterns = [
    path('', views.home, name='home'),
    # Common lowercase/typo ways people type the AI page — all land on the
    # canonical /AI/.
    path('ai/', RedirectView.as_view(url='/AI/', permanent=False)),
    path('aii/', RedirectView.as_view(url='/AI/', permanent=False)),
    path('websitecreation/', views.home2, name='home2'),
    path('websitecreation/contact/', views.websitecreation_contact, name='websitecreation_contact'),
    # Preserve old/commonly-guessed store URLs while keeping /store/ as the
    # only indexable canonical URL.
    path('estore', RedirectView.as_view(url='/store/', permanent=True, query_string=True)),
    path('estore/', RedirectView.as_view(url='/store/', permanent=True, query_string=True)),
    path('store/', views.estore, name='estore'),
    path('store/manifest.json', views.pwa_manifest, name='pwa_manifest'),
    path('store/sw.js', views.pwa_service_worker, name='pwa_service_worker'),
    path('store/api/signup/', views.store_signup, name='store_signup'),
    path('store/api/login/', views.store_login, name='store_login'),
    path('store/api/logout/', views.store_logout, name='store_logout'),
    path('store/api/profile/update/', views.store_profile_update, name='store_profile_update'),
    path('store/api/profile/password/', views.store_password_change, name='store_password_change'),
    path('store/api/profile/phone/verify/send/', views.store_phone_verify_send, name='store_phone_verify_send'),
    path('store/api/profile/phone/verify/confirm/', views.store_phone_verify_confirm, name='store_phone_verify_confirm'),
    path('store/api/cart/', views.store_cart_get, name='store_cart_get'),
    path('store/api/cart/add/', views.store_cart_add, name='store_cart_add'),
    path('store/api/cart/update/', views.store_cart_update, name='store_cart_update'),
    path('store/api/cart/remove/', views.store_cart_remove, name='store_cart_remove'),
    path('store/api/checkout/', views.store_checkout, name='store_checkout'),
    path('store/api/checkout/razorpay/verify/', views.store_razorpay_verify, name='store_razorpay_verify'),
    path('store/api/orders/', views.store_orders_list, name='store_orders_list'),
    path('store/api/orders/<int:order_id>/retry-payment/', views.store_order_retry_payment, name='store_order_retry_payment'),
    path('store/api/wallet/', views.store_wallet_get, name='store_wallet_get'),
    path('store/api/contact/', views.store_contact, name='store_contact'),

    path('store/policy/<str:key>/', views.policy_page, name='policy_page'),
    path('store/product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('store/api/product/<slug:slug>/reviews/', views.product_reviews, name='product_reviews'),
    path('store/api/product/<slug:slug>/reviews/submit/', views.product_review_submit, name='product_review_submit'),

    path('store/dashboard/', views.dashboard_home, name='dashboard_home'),
    path('store/dashboard/signups/', views.dashboard_signups, name='dashboard_signups'),
    path('store/dashboard/users/add/', views.dashboard_user_add, name='dashboard_user_add'),
    path('store/dashboard/signups/<int:pk>/edit/', views.dashboard_signup_edit, name='dashboard_signup_edit'),
    path('store/dashboard/signups/<int:pk>/delete/', views.dashboard_signup_delete, name='dashboard_signup_delete'),
    path('store/dashboard/ai/', views.dashboard_ai_management, name='dashboard_ai_management'),
    path('store/dashboard/ai/grant/', views.dashboard_ai_grant, name='dashboard_ai_grant'),
    path('store/dashboard/ai/<int:pk>/revoke/', views.dashboard_ai_revoke, name='dashboard_ai_revoke'),
    path('store/dashboard/ai/activity/', views.dashboard_ai_activity, name='dashboard_ai_activity'),
    path('store/dashboard/ai/activity/<int:pk>/', views.dashboard_ai_activity_detail, name='dashboard_ai_activity_detail'),
    path('store/dashboard/ai/activity/block/', views.dashboard_ai_block, name='dashboard_ai_block'),
    path('store/dashboard/ai/activity/unblock/<int:pk>/', views.dashboard_ai_unblock, name='dashboard_ai_unblock'),
    path('store/dashboard/contacts/', views.dashboard_contacts, name='dashboard_contacts'),
    path('store/dashboard/contacts/<int:pk>/delete/', views.dashboard_contact_delete, name='dashboard_contact_delete'),
    path('store/dashboard/categories/', views.dashboard_categories, name='dashboard_categories'),
    path('store/dashboard/categories/add/', views.dashboard_category_add, name='dashboard_category_add'),
    path('store/dashboard/categories/<int:pk>/edit/', views.dashboard_category_edit, name='dashboard_category_edit'),
    path('store/dashboard/categories/<int:pk>/delete/', views.dashboard_category_delete, name='dashboard_category_delete'),
    path('store/dashboard/products/', views.dashboard_products, name='dashboard_products'),
    path('store/dashboard/products/add/', views.dashboard_product_add, name='dashboard_product_add'),
    path('store/dashboard/products/<int:pk>/edit/', views.dashboard_product_edit, name='dashboard_product_edit'),
    path('store/dashboard/products/<int:pk>/delete/', views.dashboard_product_delete, name='dashboard_product_delete'),
    path('store/dashboard/products/seed-reviews/', views.dashboard_seed_reviews, name='dashboard_seed_reviews'),
    path('store/dashboard/about/', views.dashboard_about, name='dashboard_about'),
    path('store/dashboard/policies/', views.dashboard_policies, name='dashboard_policies'),
    path('store/dashboard/policies/<int:pk>/edit/', views.dashboard_policy_edit, name='dashboard_policy_edit'),
    path('store/dashboard/payment-settings/', views.dashboard_payment_settings, name='dashboard_payment_settings'),
    path('store/dashboard/fee-settings/', views.dashboard_fee_settings, name='dashboard_fee_settings'),
    path('store/dashboard/email-settings/', views.dashboard_email_settings, name='dashboard_email_settings'),
    path('store/dashboard/email-settings/test/', views.dashboard_email_settings_test, name='dashboard_email_settings_test'),
    path('store/dashboard/pwa-settings/', views.dashboard_pwa_settings, name='dashboard_pwa_settings'),
    path('store/dashboard/payments/', views.dashboard_payments, name='dashboard_payments'),
    path('store/dashboard/backup/', views.dashboard_backup, name='dashboard_backup'),
    path('store/dashboard/backup/settings/', views.dashboard_backup_settings, name='dashboard_backup_settings'),
    path('store/dashboard/backup/run/', views.dashboard_backup_run, name='dashboard_backup_run'),
    path('store/dashboard/backup/restore/', views.dashboard_backup_restore, name='dashboard_backup_restore'),
    path('store/dashboard/orders/', views.dashboard_orders, name='dashboard_orders'),
    path('store/dashboard/orders/<int:pk>/status/', views.dashboard_order_status_update, name='dashboard_order_status_update'),
    path('store/dashboard/delivery/', views.dashboard_delivery, name='dashboard_delivery'),
    path('store/dashboard/logout/', views.dashboard_logout, name='dashboard_logout'),

    path('contact/', views.contact_lead, name='contact_lead'),

    path('AI/', views.ai_page, name='ai_page'),
    path('AI/manifest.json', views.ai_manifest, name='ai_manifest'),
    path('AI/sw.js', views.pwa_service_worker, name='ai_service_worker'),
    path('AI/api/send/', views.ai_chat_send, name='ai_chat_send'),
    path('AI/api/extract/', views.ai_extract_document, name='ai_extract_document'),
    path('AI/api/transcribe/', views.ai_transcribe_audio, name='ai_transcribe_audio'),
    path('AI/api/youtube/start/', views.ai_youtube_start, name='ai_youtube_start'),
    path('AI/api/youtube/<uuid:token>/status/', views.ai_youtube_status, name='ai_youtube_status'),
    path('AI/api/youtube/<uuid:token>/file/<str:file_kind>/', views.ai_youtube_file, name='ai_youtube_file'),
    path('AI/api/conversations/', views.ai_conversations_list, name='ai_conversations_list'),
    path('AI/api/conversations/<int:conversation_id>/', views.ai_conversation_messages, name='ai_conversation_messages'),
    path('AI/api/conversations/<int:conversation_id>/delete/', views.ai_conversation_delete, name='ai_conversation_delete'),
    path('AI/api/notes/', views.ai_notes_list, name='ai_notes_list'),
    path('AI/api/notes/<int:note_id>/delete/', views.ai_note_delete, name='ai_note_delete'),
    path('AI/api/report/', views.ai_report_submit, name='ai_report_submit'),

    path('AI/api/github/status/', views.github_status, name='github_status'),
    path('AI/api/github/oauth/start/', views.github_oauth_start, name='github_oauth_start'),
    path('AI/api/github/oauth/callback/', views.github_oauth_callback, name='github_oauth_callback'),
    path('AI/api/github/connect/', views.github_connect, name='github_connect'),
    path('AI/api/github/repos/', views.github_repos, name='github_repos'),
    path('AI/api/github/repo/', views.github_set_repo, name='github_set_repo'),
    path('AI/api/github/disconnect/', views.github_disconnect, name='github_disconnect'),
    path('AI/api/github/send/', views.ai_github_send, name='ai_github_send'),
]
